// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module alignment_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ref_imgs_V_address0,
        ref_imgs_V_ce0,
        ref_imgs_V_q0,
        ref_imgs_V_address1,
        ref_imgs_V_ce1,
        ref_imgs_V_q1,
        alt_imgs_V_address0,
        alt_imgs_V_ce0,
        alt_imgs_V_q0,
        alt_imgs_V_address1,
        alt_imgs_V_ce1,
        alt_imgs_V_q1,
        align_x,
        align_x_ap_vld,
        align_y,
        align_y_ap_vld
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] ref_imgs_V_address0;
output   ref_imgs_V_ce0;
input  [15:0] ref_imgs_V_q0;
output  [7:0] ref_imgs_V_address1;
output   ref_imgs_V_ce1;
input  [15:0] ref_imgs_V_q1;
output  [9:0] alt_imgs_V_address0;
output   alt_imgs_V_ce0;
input  [15:0] alt_imgs_V_q0;
output  [9:0] alt_imgs_V_address1;
output   alt_imgs_V_ce1;
input  [15:0] alt_imgs_V_q1;
output  [31:0] align_x;
output   align_x_ap_vld;
output  [31:0] align_y;
output   align_y_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] ref_imgs_V_address0;
reg ref_imgs_V_ce0;
reg[7:0] ref_imgs_V_address1;
reg ref_imgs_V_ce1;
reg[9:0] alt_imgs_V_address0;
reg alt_imgs_V_ce0;
reg[9:0] alt_imgs_V_address1;
reg alt_imgs_V_ce1;
reg align_x_ap_vld;
reg align_y_ap_vld;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] i_cast_fu_465_p1;
reg   [4:0] i_cast_reg_1816;
wire    ap_CS_fsm_state2;
wire   [3:0] i_1_fu_475_p2;
reg   [3:0] i_1_reg_1824;
wire  signed [31:0] align_x_assign_cast_fu_487_p1;
reg  signed [31:0] align_x_assign_cast_reg_1829;
wire   [0:0] exitcond1_fu_469_p2;
wire   [3:0] j_1_fu_501_p2;
reg   [3:0] j_1_reg_1837;
wire    ap_CS_fsm_state3;
wire   [10:0] tmp_7_cast_fu_507_p1;
reg   [10:0] tmp_7_cast_reg_1842;
wire   [0:0] exitcond2_fu_495_p2;
wire   [10:0] tmp_7_1_cast_fu_511_p1;
reg   [10:0] tmp_7_1_cast_reg_1847;
wire   [10:0] tmp_7_2_cast_fu_521_p1;
reg   [10:0] tmp_7_2_cast_reg_1852;
wire   [10:0] tmp_7_3_cast_fu_531_p1;
reg   [10:0] tmp_7_3_cast_reg_1857;
wire   [10:0] tmp_7_4_cast_fu_541_p1;
reg   [10:0] tmp_7_4_cast_reg_1862;
wire   [10:0] tmp_7_5_cast_fu_551_p1;
reg   [10:0] tmp_7_5_cast_reg_1867;
wire   [10:0] tmp_7_6_cast_fu_561_p1;
reg   [10:0] tmp_7_6_cast_reg_1872;
wire   [10:0] tmp_7_7_cast_fu_571_p1;
reg   [10:0] tmp_7_7_cast_reg_1877;
wire   [10:0] tmp_7_8_cast_fu_581_p1;
reg   [10:0] tmp_7_8_cast_reg_1882;
wire   [10:0] tmp_7_9_cast_fu_591_p1;
reg   [10:0] tmp_7_9_cast_reg_1887;
wire   [10:0] tmp_7_cast_3_fu_601_p1;
reg   [10:0] tmp_7_cast_3_reg_1892;
wire   [10:0] tmp_7_10_cast_fu_611_p1;
reg   [10:0] tmp_7_10_cast_reg_1897;
wire   [10:0] tmp_7_11_cast_fu_621_p1;
reg   [10:0] tmp_7_11_cast_reg_1902;
wire   [10:0] tmp_7_12_cast_fu_631_p1;
reg   [10:0] tmp_7_12_cast_reg_1907;
wire   [10:0] tmp_7_13_cast_fu_641_p1;
reg   [10:0] tmp_7_13_cast_reg_1912;
wire   [10:0] tmp_7_14_cast_fu_651_p1;
reg   [10:0] tmp_7_14_cast_reg_1917;
wire   [4:0] n_1_fu_661_p2;
reg   [4:0] n_1_reg_1925;
wire    ap_CS_fsm_state4;
wire   [8:0] tmp_3_fu_667_p3;
reg   [8:0] tmp_3_reg_1930;
wire   [0:0] exitcond3_fu_655_p2;
wire   [10:0] tmp_41_fu_750_p2;
reg   [10:0] tmp_41_reg_1968;
wire   [10:0] tmp_42_fu_755_p2;
reg   [10:0] tmp_42_reg_1973;
wire   [10:0] tmp_43_fu_760_p2;
reg   [10:0] tmp_43_reg_1978;
wire   [10:0] tmp_44_fu_765_p2;
reg   [10:0] tmp_44_reg_1983;
wire   [10:0] tmp_45_fu_770_p2;
reg   [10:0] tmp_45_reg_1988;
wire   [10:0] tmp_46_fu_775_p2;
reg   [10:0] tmp_46_reg_1993;
wire   [10:0] tmp_47_fu_780_p2;
reg   [10:0] tmp_47_reg_1998;
wire   [10:0] tmp_48_fu_785_p2;
reg   [10:0] tmp_48_reg_2003;
wire   [10:0] tmp_49_fu_790_p2;
reg   [10:0] tmp_49_reg_2008;
wire   [10:0] tmp_50_fu_795_p2;
reg   [10:0] tmp_50_reg_2013;
wire   [10:0] tmp_51_fu_800_p2;
reg   [10:0] tmp_51_reg_2018;
wire   [10:0] tmp_52_fu_805_p2;
reg   [10:0] tmp_52_reg_2023;
wire   [10:0] tmp_53_fu_810_p2;
reg   [10:0] tmp_53_reg_2028;
wire   [10:0] tmp_54_fu_815_p2;
reg   [10:0] tmp_54_reg_2033;
wire    ap_CS_fsm_state5;
wire   [16:0] ret_V_fu_893_p2;
reg   [16:0] ret_V_reg_2061;
wire   [16:0] ret_V_1_fu_907_p2;
reg   [16:0] ret_V_1_reg_2068;
wire    ap_CS_fsm_state6;
wire   [16:0] ret_V_2_fu_999_p2;
reg   [16:0] ret_V_2_reg_2095;
wire   [16:0] ret_V_3_fu_1013_p2;
reg   [16:0] ret_V_3_reg_2102;
wire   [17:0] tmp3_fu_1019_p2;
reg   [17:0] tmp3_reg_2109;
wire    ap_CS_fsm_state7;
wire   [16:0] ret_V_4_fu_1111_p2;
reg   [16:0] ret_V_4_reg_2134;
wire   [16:0] ret_V_5_fu_1125_p2;
reg   [16:0] ret_V_5_reg_2141;
wire   [18:0] tmp2_fu_1144_p2;
reg   [18:0] tmp2_reg_2148;
wire    ap_CS_fsm_state8;
wire   [16:0] ret_V_6_fu_1236_p2;
reg   [16:0] ret_V_6_reg_2173;
wire   [0:0] abscond_6_fu_1242_p2;
reg   [0:0] abscond_6_reg_2179;
wire   [16:0] ret_V_7_fu_1256_p2;
reg   [16:0] ret_V_7_reg_2184;
wire   [0:0] abscond_7_fu_1262_p2;
reg   [0:0] abscond_7_reg_2190;
wire   [17:0] tmp6_fu_1268_p2;
reg   [17:0] tmp6_reg_2195;
wire    ap_CS_fsm_state9;
wire   [16:0] ret_V_8_fu_1348_p2;
reg   [16:0] ret_V_8_reg_2220;
wire   [16:0] ret_V_9_fu_1362_p2;
reg   [16:0] ret_V_9_reg_2227;
wire   [19:0] tmp1_fu_1394_p2;
reg   [19:0] tmp1_reg_2234;
wire    ap_CS_fsm_state10;
wire   [16:0] ret_V_s_fu_1486_p2;
reg   [16:0] ret_V_s_reg_2259;
wire   [16:0] ret_V_10_fu_1500_p2;
reg   [16:0] ret_V_10_reg_2266;
wire   [17:0] tmp10_fu_1506_p2;
reg   [17:0] tmp10_reg_2273;
wire    ap_CS_fsm_state11;
wire   [16:0] ret_V_11_fu_1598_p2;
reg   [16:0] ret_V_11_reg_2298;
wire   [16:0] ret_V_12_fu_1612_p2;
reg   [16:0] ret_V_12_reg_2305;
wire   [18:0] tmp9_fu_1631_p2;
reg   [18:0] tmp9_reg_2312;
wire   [16:0] ret_V_13_fu_1687_p2;
reg   [16:0] ret_V_13_reg_2317;
wire    ap_CS_fsm_state12;
wire   [0:0] abscond_13_fu_1693_p2;
reg   [0:0] abscond_13_reg_2323;
wire   [16:0] ret_V_14_fu_1707_p2;
reg   [16:0] ret_V_14_reg_2328;
wire   [0:0] abscond_14_fu_1713_p2;
reg   [0:0] abscond_14_reg_2334;
wire   [17:0] tmp13_fu_1719_p2;
reg   [17:0] tmp13_reg_2339;
wire   [19:0] tmp8_fu_1781_p2;
reg   [19:0] tmp8_reg_2344;
wire    ap_CS_fsm_state13;
wire   [24:0] temp_sum_s_fu_1803_p2;
wire    ap_CS_fsm_state14;
reg   [3:0] i_reg_414;
reg   [3:0] j_reg_425;
reg  signed [24:0] sum_1_reg_437;
reg   [4:0] n_reg_449;
wire   [63:0] tmp_5_fu_675_p1;
wire   [63:0] tmp_8_fu_686_p3;
wire  signed [63:0] tmp_41_cast_fu_735_p1;
wire  signed [63:0] tmp_42_cast_fu_745_p1;
wire   [63:0] tmp_7_fu_854_p3;
wire   [63:0] tmp_11_fu_868_p3;
wire  signed [63:0] tmp_43_cast_fu_877_p1;
wire  signed [63:0] tmp_44_cast_fu_881_p1;
wire   [63:0] tmp_13_fu_918_p3;
wire   [63:0] tmp_15_fu_932_p3;
wire  signed [63:0] tmp_45_cast_fu_941_p1;
wire  signed [63:0] tmp_46_cast_fu_945_p1;
wire   [63:0] tmp_17_fu_1030_p3;
wire   [63:0] tmp_19_fu_1044_p3;
wire  signed [63:0] tmp_47_cast_fu_1053_p1;
wire  signed [63:0] tmp_48_cast_fu_1057_p1;
wire   [63:0] tmp_21_fu_1155_p3;
wire   [63:0] tmp_23_fu_1169_p3;
wire  signed [63:0] tmp_49_cast_fu_1178_p1;
wire  signed [63:0] tmp_50_cast_fu_1182_p1;
wire   [63:0] tmp_25_fu_1279_p3;
wire   [63:0] tmp_27_fu_1293_p3;
wire  signed [63:0] tmp_51_cast_fu_1302_p1;
wire  signed [63:0] tmp_52_cast_fu_1306_p1;
wire   [63:0] tmp_29_fu_1405_p3;
wire   [63:0] tmp_31_fu_1419_p3;
wire  signed [63:0] tmp_53_cast_fu_1428_p1;
wire  signed [63:0] tmp_54_cast_fu_1432_p1;
wire   [63:0] tmp_33_fu_1517_p3;
wire   [63:0] tmp_35_fu_1531_p3;
wire  signed [63:0] tmp_55_cast_fu_1540_p1;
wire  signed [63:0] tmp_56_cast_fu_1544_p1;
reg   [31:0] sum_fu_122;
wire  signed [31:0] sum_3_cast_fu_823_p1;
wire   [0:0] tmp_2_fu_827_p2;
wire   [3:0] align_x_assign_fu_481_p2;
wire   [3:0] tmp_6_2_fu_515_p2;
wire   [3:0] tmp_6_3_fu_525_p2;
wire   [3:0] tmp_6_4_fu_535_p2;
wire   [3:0] tmp_6_5_fu_545_p2;
wire   [3:0] tmp_6_6_fu_555_p2;
wire   [3:0] tmp_6_7_fu_565_p2;
wire   [4:0] j_cast_fu_491_p1;
wire   [4:0] tmp_6_8_fu_575_p2;
wire   [4:0] tmp_6_9_fu_585_p2;
wire   [4:0] tmp_6_s_fu_595_p2;
wire   [4:0] tmp_6_1_fu_605_p2;
wire   [4:0] tmp_6_10_fu_615_p2;
wire   [4:0] tmp_6_11_fu_625_p2;
wire   [4:0] tmp_6_12_fu_635_p2;
wire   [4:0] tmp_6_13_fu_645_p2;
wire   [8:0] tmp_6_fu_680_p2;
wire   [4:0] tmp_4_fu_695_p2;
wire   [9:0] tmp_36_fu_700_p3;
wire   [7:0] tmp_37_fu_712_p3;
wire   [10:0] p_shl_cast_fu_708_p1;
wire   [10:0] p_shl1_cast_fu_720_p1;
wire   [10:0] tmp_38_fu_724_p2;
wire   [10:0] tmp_39_fu_730_p2;
wire   [10:0] tmp_40_fu_740_p2;
wire   [3:0] align_y_assign_fu_833_p2;
wire   [8:0] tmp_9_fu_849_p2;
wire   [8:0] tmp_10_fu_863_p2;
wire   [16:0] lhs_V_fu_885_p1;
wire   [16:0] rhs_V_fu_889_p1;
wire   [16:0] lhs_V_1_fu_899_p1;
wire   [16:0] rhs_V_1_fu_903_p1;
wire   [8:0] tmp_12_fu_913_p2;
wire   [8:0] tmp_14_fu_927_p2;
wire   [0:0] abscond_fu_954_p2;
wire   [16:0] neg_fu_949_p2;
wire   [16:0] abs_fu_959_p3;
wire   [0:0] abscond_1_fu_975_p2;
wire   [16:0] neg_1_fu_970_p2;
wire   [16:0] abs_1_fu_980_p3;
wire   [16:0] lhs_V_2_fu_991_p1;
wire   [16:0] rhs_V_2_fu_995_p1;
wire   [16:0] lhs_V_3_fu_1005_p1;
wire   [16:0] rhs_V_3_fu_1009_p1;
wire  signed [17:0] abs_cast_fu_966_p1;
wire  signed [17:0] abs_1_cast_fu_987_p1;
wire   [8:0] tmp_16_fu_1025_p2;
wire   [8:0] tmp_18_fu_1039_p2;
wire   [0:0] abscond_2_fu_1066_p2;
wire   [16:0] neg_2_fu_1061_p2;
wire   [16:0] abs_2_fu_1071_p3;
wire   [0:0] abscond_3_fu_1087_p2;
wire   [16:0] neg_3_fu_1082_p2;
wire   [16:0] abs_3_fu_1092_p3;
wire   [16:0] lhs_V_4_fu_1103_p1;
wire   [16:0] rhs_V_4_fu_1107_p1;
wire   [16:0] lhs_V_5_fu_1117_p1;
wire   [16:0] rhs_V_5_fu_1121_p1;
wire  signed [17:0] abs_2_cast_fu_1078_p1;
wire  signed [17:0] abs_3_cast_fu_1099_p1;
wire   [17:0] tmp4_fu_1134_p2;
wire  signed [18:0] tmp4_cast_fu_1140_p1;
wire  signed [18:0] tmp3_cast_fu_1131_p1;
wire   [8:0] tmp_20_fu_1150_p2;
wire   [8:0] tmp_22_fu_1164_p2;
wire   [0:0] abscond_4_fu_1191_p2;
wire   [16:0] neg_4_fu_1186_p2;
wire   [16:0] abs_4_fu_1196_p3;
wire   [0:0] abscond_5_fu_1212_p2;
wire   [16:0] neg_5_fu_1207_p2;
wire   [16:0] abs_5_fu_1217_p3;
wire   [16:0] lhs_V_6_fu_1228_p1;
wire   [16:0] rhs_V_6_fu_1232_p1;
wire   [16:0] lhs_V_7_fu_1248_p1;
wire   [16:0] rhs_V_7_fu_1252_p1;
wire  signed [17:0] abs_4_cast_fu_1203_p1;
wire  signed [17:0] abs_5_cast_fu_1224_p1;
wire   [8:0] tmp_24_fu_1274_p2;
wire   [8:0] tmp_26_fu_1288_p2;
wire   [16:0] neg_6_fu_1310_p2;
wire   [16:0] abs_6_fu_1315_p3;
wire   [16:0] neg_7_fu_1325_p2;
wire   [16:0] abs_7_fu_1330_p3;
wire   [16:0] lhs_V_8_fu_1340_p1;
wire   [16:0] rhs_V_8_fu_1344_p1;
wire   [16:0] lhs_V_9_fu_1354_p1;
wire   [16:0] rhs_V_9_fu_1358_p1;
wire  signed [17:0] abs_6_cast_fu_1321_p1;
wire  signed [17:0] abs_7_cast_fu_1336_p1;
wire   [17:0] tmp7_fu_1374_p2;
wire  signed [18:0] tmp7_cast_fu_1380_p1;
wire  signed [18:0] tmp6_cast_fu_1371_p1;
wire   [18:0] tmp5_fu_1384_p2;
wire  signed [19:0] tmp5_cast_fu_1390_p1;
wire  signed [19:0] tmp2_cast_fu_1368_p1;
wire   [8:0] tmp_28_fu_1400_p2;
wire   [8:0] tmp_30_fu_1414_p2;
wire   [0:0] abscond_8_fu_1441_p2;
wire   [16:0] neg_8_fu_1436_p2;
wire   [16:0] abs_8_fu_1446_p3;
wire   [0:0] abscond_9_fu_1462_p2;
wire   [16:0] neg_9_fu_1457_p2;
wire   [16:0] abs_9_fu_1467_p3;
wire   [16:0] lhs_V_s_fu_1478_p1;
wire   [16:0] rhs_V_s_fu_1482_p1;
wire   [16:0] lhs_V_10_fu_1492_p1;
wire   [16:0] rhs_V_10_fu_1496_p1;
wire  signed [17:0] abs_8_cast_fu_1453_p1;
wire  signed [17:0] abs_9_cast_fu_1474_p1;
wire   [8:0] tmp_32_fu_1512_p2;
wire   [8:0] tmp_34_fu_1526_p2;
wire   [0:0] abscond_s_fu_1553_p2;
wire   [16:0] neg_s_fu_1548_p2;
wire   [16:0] abs_s_fu_1558_p3;
wire   [0:0] abscond_10_fu_1574_p2;
wire   [16:0] neg_10_fu_1569_p2;
wire   [16:0] abs_10_fu_1579_p3;
wire   [16:0] lhs_V_11_fu_1590_p1;
wire   [16:0] rhs_V_11_fu_1594_p1;
wire   [16:0] lhs_V_12_fu_1604_p1;
wire   [16:0] rhs_V_12_fu_1608_p1;
wire  signed [17:0] abs_cast_5_fu_1565_p1;
wire  signed [17:0] abs_10_cast_fu_1586_p1;
wire   [17:0] tmp11_fu_1621_p2;
wire  signed [18:0] tmp11_cast_fu_1627_p1;
wire  signed [18:0] tmp10_cast_fu_1618_p1;
wire   [0:0] abscond_11_fu_1642_p2;
wire   [16:0] neg_11_fu_1637_p2;
wire   [16:0] abs_11_fu_1647_p3;
wire   [0:0] abscond_12_fu_1663_p2;
wire   [16:0] neg_12_fu_1658_p2;
wire   [16:0] abs_12_fu_1668_p3;
wire   [16:0] lhs_V_13_fu_1679_p1;
wire   [16:0] rhs_V_13_fu_1683_p1;
wire   [16:0] lhs_V_14_fu_1699_p1;
wire   [16:0] rhs_V_14_fu_1703_p1;
wire  signed [17:0] abs_11_cast_fu_1654_p1;
wire  signed [17:0] abs_12_cast_fu_1675_p1;
wire   [16:0] neg_13_fu_1725_p2;
wire   [16:0] abs_13_fu_1730_p3;
wire   [16:0] neg_14_fu_1740_p2;
wire   [16:0] abs_14_fu_1745_p3;
wire  signed [17:0] abs_13_cast_fu_1736_p1;
wire  signed [17:0] abs_14_cast_fu_1751_p1;
wire   [17:0] tmp14_fu_1761_p2;
wire  signed [18:0] tmp14_cast_fu_1767_p1;
wire  signed [18:0] tmp13_cast_fu_1758_p1;
wire   [18:0] tmp12_fu_1771_p2;
wire  signed [19:0] tmp12_cast_fu_1777_p1;
wire  signed [19:0] tmp9_cast_fu_1755_p1;
wire  signed [20:0] tmp8_cast_fu_1790_p1;
wire  signed [20:0] tmp1_cast_fu_1787_p1;
wire   [20:0] tmp_s_fu_1793_p2;
wire  signed [24:0] p_cast_fu_1799_p1;
reg   [13:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_495_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_414 <= i_1_reg_1824;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_414 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond3_fu_655_p2 == 1'd1))) begin
        j_reg_425 <= j_1_reg_1837;
    end else if (((exitcond1_fu_469_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_425 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        n_reg_449 <= n_1_reg_1925;
    end else if (((exitcond2_fu_495_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        n_reg_449 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sum_1_reg_437 <= temp_sum_s_fu_1803_p2;
    end else if (((exitcond2_fu_495_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        sum_1_reg_437 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_827_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (exitcond3_fu_655_p2 == 1'd1))) begin
        sum_fu_122 <= sum_3_cast_fu_823_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sum_fu_122 <= 32'd10000;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        abscond_13_reg_2323 <= abscond_13_fu_1693_p2;
        abscond_14_reg_2334 <= abscond_14_fu_1713_p2;
        ret_V_13_reg_2317 <= ret_V_13_fu_1687_p2;
        ret_V_14_reg_2328 <= ret_V_14_fu_1707_p2;
        tmp13_reg_2339 <= tmp13_fu_1719_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        abscond_6_reg_2179 <= abscond_6_fu_1242_p2;
        abscond_7_reg_2190 <= abscond_7_fu_1262_p2;
        ret_V_6_reg_2173 <= ret_V_6_fu_1236_p2;
        ret_V_7_reg_2184 <= ret_V_7_fu_1256_p2;
        tmp6_reg_2195 <= tmp6_fu_1268_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_469_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        align_x_assign_cast_reg_1829 <= align_x_assign_cast_fu_487_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_1824 <= i_1_fu_475_p2;
        i_cast_reg_1816[3 : 0] <= i_cast_fu_465_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_1_reg_1837 <= j_1_fu_501_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        n_1_reg_1925 <= n_1_fu_661_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ret_V_10_reg_2266 <= ret_V_10_fu_1500_p2;
        ret_V_s_reg_2259 <= ret_V_s_fu_1486_p2;
        tmp10_reg_2273 <= tmp10_fu_1506_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ret_V_11_reg_2298 <= ret_V_11_fu_1598_p2;
        ret_V_12_reg_2305 <= ret_V_12_fu_1612_p2;
        tmp9_reg_2312 <= tmp9_fu_1631_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ret_V_1_reg_2068 <= ret_V_1_fu_907_p2;
        ret_V_reg_2061 <= ret_V_fu_893_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ret_V_2_reg_2095 <= ret_V_2_fu_999_p2;
        ret_V_3_reg_2102 <= ret_V_3_fu_1013_p2;
        tmp3_reg_2109 <= tmp3_fu_1019_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ret_V_4_reg_2134 <= ret_V_4_fu_1111_p2;
        ret_V_5_reg_2141 <= ret_V_5_fu_1125_p2;
        tmp2_reg_2148 <= tmp2_fu_1144_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ret_V_8_reg_2220 <= ret_V_8_fu_1348_p2;
        ret_V_9_reg_2227 <= ret_V_9_fu_1362_p2;
        tmp1_reg_2234 <= tmp1_fu_1394_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp8_reg_2344 <= tmp8_fu_1781_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_3_reg_1930[8 : 4] <= tmp_3_fu_667_p3[8 : 4];
        tmp_41_reg_1968 <= tmp_41_fu_750_p2;
        tmp_42_reg_1973 <= tmp_42_fu_755_p2;
        tmp_43_reg_1978 <= tmp_43_fu_760_p2;
        tmp_44_reg_1983 <= tmp_44_fu_765_p2;
        tmp_45_reg_1988 <= tmp_45_fu_770_p2;
        tmp_46_reg_1993 <= tmp_46_fu_775_p2;
        tmp_47_reg_1998 <= tmp_47_fu_780_p2;
        tmp_48_reg_2003 <= tmp_48_fu_785_p2;
        tmp_49_reg_2008 <= tmp_49_fu_790_p2;
        tmp_50_reg_2013 <= tmp_50_fu_795_p2;
        tmp_51_reg_2018 <= tmp_51_fu_800_p2;
        tmp_52_reg_2023 <= tmp_52_fu_805_p2;
        tmp_53_reg_2028 <= tmp_53_fu_810_p2;
        tmp_54_reg_2033 <= tmp_54_fu_815_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_495_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_7_10_cast_reg_1897[4 : 0] <= tmp_7_10_cast_fu_611_p1[4 : 0];
        tmp_7_11_cast_reg_1902[4 : 0] <= tmp_7_11_cast_fu_621_p1[4 : 0];
        tmp_7_12_cast_reg_1907[4 : 0] <= tmp_7_12_cast_fu_631_p1[4 : 0];
        tmp_7_13_cast_reg_1912[4 : 0] <= tmp_7_13_cast_fu_641_p1[4 : 0];
        tmp_7_14_cast_reg_1917[4 : 0] <= tmp_7_14_cast_fu_651_p1[4 : 0];
        tmp_7_1_cast_reg_1847[3 : 0] <= tmp_7_1_cast_fu_511_p1[3 : 0];
        tmp_7_2_cast_reg_1852[3 : 0] <= tmp_7_2_cast_fu_521_p1[3 : 0];
        tmp_7_3_cast_reg_1857[3 : 0] <= tmp_7_3_cast_fu_531_p1[3 : 0];
        tmp_7_4_cast_reg_1862[3 : 0] <= tmp_7_4_cast_fu_541_p1[3 : 0];
        tmp_7_5_cast_reg_1867[3 : 0] <= tmp_7_5_cast_fu_551_p1[3 : 0];
        tmp_7_6_cast_reg_1872[3 : 0] <= tmp_7_6_cast_fu_561_p1[3 : 0];
        tmp_7_7_cast_reg_1877[3 : 0] <= tmp_7_7_cast_fu_571_p1[3 : 0];
        tmp_7_8_cast_reg_1882[4 : 0] <= tmp_7_8_cast_fu_581_p1[4 : 0];
        tmp_7_9_cast_reg_1887[4 : 0] <= tmp_7_9_cast_fu_591_p1[4 : 0];
        tmp_7_cast_3_reg_1892[4 : 0] <= tmp_7_cast_3_fu_601_p1[4 : 0];
        tmp_7_cast_reg_1842[3 : 0] <= tmp_7_cast_fu_507_p1[3 : 0];
    end
end

always @ (*) begin
    if (((tmp_2_fu_827_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (exitcond3_fu_655_p2 == 1'd1))) begin
        align_x_ap_vld = 1'b1;
    end else begin
        align_x_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_fu_827_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (exitcond3_fu_655_p2 == 1'd1))) begin
        align_y_ap_vld = 1'b1;
    end else begin
        align_y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        alt_imgs_V_address0 = tmp_55_cast_fu_1540_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        alt_imgs_V_address0 = tmp_53_cast_fu_1428_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        alt_imgs_V_address0 = tmp_51_cast_fu_1302_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        alt_imgs_V_address0 = tmp_49_cast_fu_1178_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        alt_imgs_V_address0 = tmp_47_cast_fu_1053_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        alt_imgs_V_address0 = tmp_45_cast_fu_941_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        alt_imgs_V_address0 = tmp_43_cast_fu_877_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        alt_imgs_V_address0 = tmp_41_cast_fu_735_p1;
    end else begin
        alt_imgs_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        alt_imgs_V_address1 = tmp_56_cast_fu_1544_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        alt_imgs_V_address1 = tmp_54_cast_fu_1432_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        alt_imgs_V_address1 = tmp_52_cast_fu_1306_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        alt_imgs_V_address1 = tmp_50_cast_fu_1182_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        alt_imgs_V_address1 = tmp_48_cast_fu_1057_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        alt_imgs_V_address1 = tmp_46_cast_fu_945_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        alt_imgs_V_address1 = tmp_44_cast_fu_881_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        alt_imgs_V_address1 = tmp_42_cast_fu_745_p1;
    end else begin
        alt_imgs_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        alt_imgs_V_ce0 = 1'b1;
    end else begin
        alt_imgs_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        alt_imgs_V_ce1 = 1'b1;
    end else begin
        alt_imgs_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((exitcond1_fu_469_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_469_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ref_imgs_V_address0 = tmp_33_fu_1517_p3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        ref_imgs_V_address0 = tmp_29_fu_1405_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        ref_imgs_V_address0 = tmp_25_fu_1279_p3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        ref_imgs_V_address0 = tmp_21_fu_1155_p3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        ref_imgs_V_address0 = tmp_17_fu_1030_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        ref_imgs_V_address0 = tmp_13_fu_918_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        ref_imgs_V_address0 = tmp_7_fu_854_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        ref_imgs_V_address0 = tmp_5_fu_675_p1;
    end else begin
        ref_imgs_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ref_imgs_V_address1 = tmp_35_fu_1531_p3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        ref_imgs_V_address1 = tmp_31_fu_1419_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        ref_imgs_V_address1 = tmp_27_fu_1293_p3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        ref_imgs_V_address1 = tmp_23_fu_1169_p3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        ref_imgs_V_address1 = tmp_19_fu_1044_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        ref_imgs_V_address1 = tmp_15_fu_932_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        ref_imgs_V_address1 = tmp_11_fu_868_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        ref_imgs_V_address1 = tmp_8_fu_686_p3;
    end else begin
        ref_imgs_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        ref_imgs_V_ce0 = 1'b1;
    end else begin
        ref_imgs_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        ref_imgs_V_ce1 = 1'b1;
    end else begin
        ref_imgs_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_fu_469_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond2_fu_495_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (exitcond3_fu_655_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_10_cast_fu_1586_p1 = $signed(abs_10_fu_1579_p3);

assign abs_10_fu_1579_p3 = ((abscond_10_fu_1574_p2[0:0] === 1'b1) ? ret_V_10_reg_2266 : neg_10_fu_1569_p2);

assign abs_11_cast_fu_1654_p1 = $signed(abs_11_fu_1647_p3);

assign abs_11_fu_1647_p3 = ((abscond_11_fu_1642_p2[0:0] === 1'b1) ? ret_V_11_reg_2298 : neg_11_fu_1637_p2);

assign abs_12_cast_fu_1675_p1 = $signed(abs_12_fu_1668_p3);

assign abs_12_fu_1668_p3 = ((abscond_12_fu_1663_p2[0:0] === 1'b1) ? ret_V_12_reg_2305 : neg_12_fu_1658_p2);

assign abs_13_cast_fu_1736_p1 = $signed(abs_13_fu_1730_p3);

assign abs_13_fu_1730_p3 = ((abscond_13_reg_2323[0:0] === 1'b1) ? ret_V_13_reg_2317 : neg_13_fu_1725_p2);

assign abs_14_cast_fu_1751_p1 = $signed(abs_14_fu_1745_p3);

assign abs_14_fu_1745_p3 = ((abscond_14_reg_2334[0:0] === 1'b1) ? ret_V_14_reg_2328 : neg_14_fu_1740_p2);

assign abs_1_cast_fu_987_p1 = $signed(abs_1_fu_980_p3);

assign abs_1_fu_980_p3 = ((abscond_1_fu_975_p2[0:0] === 1'b1) ? ret_V_1_reg_2068 : neg_1_fu_970_p2);

assign abs_2_cast_fu_1078_p1 = $signed(abs_2_fu_1071_p3);

assign abs_2_fu_1071_p3 = ((abscond_2_fu_1066_p2[0:0] === 1'b1) ? ret_V_2_reg_2095 : neg_2_fu_1061_p2);

assign abs_3_cast_fu_1099_p1 = $signed(abs_3_fu_1092_p3);

assign abs_3_fu_1092_p3 = ((abscond_3_fu_1087_p2[0:0] === 1'b1) ? ret_V_3_reg_2102 : neg_3_fu_1082_p2);

assign abs_4_cast_fu_1203_p1 = $signed(abs_4_fu_1196_p3);

assign abs_4_fu_1196_p3 = ((abscond_4_fu_1191_p2[0:0] === 1'b1) ? ret_V_4_reg_2134 : neg_4_fu_1186_p2);

assign abs_5_cast_fu_1224_p1 = $signed(abs_5_fu_1217_p3);

assign abs_5_fu_1217_p3 = ((abscond_5_fu_1212_p2[0:0] === 1'b1) ? ret_V_5_reg_2141 : neg_5_fu_1207_p2);

assign abs_6_cast_fu_1321_p1 = $signed(abs_6_fu_1315_p3);

assign abs_6_fu_1315_p3 = ((abscond_6_reg_2179[0:0] === 1'b1) ? ret_V_6_reg_2173 : neg_6_fu_1310_p2);

assign abs_7_cast_fu_1336_p1 = $signed(abs_7_fu_1330_p3);

assign abs_7_fu_1330_p3 = ((abscond_7_reg_2190[0:0] === 1'b1) ? ret_V_7_reg_2184 : neg_7_fu_1325_p2);

assign abs_8_cast_fu_1453_p1 = $signed(abs_8_fu_1446_p3);

assign abs_8_fu_1446_p3 = ((abscond_8_fu_1441_p2[0:0] === 1'b1) ? ret_V_8_reg_2220 : neg_8_fu_1436_p2);

assign abs_9_cast_fu_1474_p1 = $signed(abs_9_fu_1467_p3);

assign abs_9_fu_1467_p3 = ((abscond_9_fu_1462_p2[0:0] === 1'b1) ? ret_V_9_reg_2227 : neg_9_fu_1457_p2);

assign abs_cast_5_fu_1565_p1 = $signed(abs_s_fu_1558_p3);

assign abs_cast_fu_966_p1 = $signed(abs_fu_959_p3);

assign abs_fu_959_p3 = ((abscond_fu_954_p2[0:0] === 1'b1) ? ret_V_reg_2061 : neg_fu_949_p2);

assign abs_s_fu_1558_p3 = ((abscond_s_fu_1553_p2[0:0] === 1'b1) ? ret_V_s_reg_2259 : neg_s_fu_1548_p2);

assign abscond_10_fu_1574_p2 = (($signed(ret_V_10_reg_2266) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_11_fu_1642_p2 = (($signed(ret_V_11_reg_2298) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_12_fu_1663_p2 = (($signed(ret_V_12_reg_2305) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_13_fu_1693_p2 = (($signed(ret_V_13_fu_1687_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_14_fu_1713_p2 = (($signed(ret_V_14_fu_1707_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_1_fu_975_p2 = (($signed(ret_V_1_reg_2068) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_2_fu_1066_p2 = (($signed(ret_V_2_reg_2095) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_3_fu_1087_p2 = (($signed(ret_V_3_reg_2102) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_4_fu_1191_p2 = (($signed(ret_V_4_reg_2134) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_5_fu_1212_p2 = (($signed(ret_V_5_reg_2141) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_6_fu_1242_p2 = (($signed(ret_V_6_fu_1236_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_7_fu_1262_p2 = (($signed(ret_V_7_fu_1256_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_8_fu_1441_p2 = (($signed(ret_V_8_reg_2220) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_9_fu_1462_p2 = (($signed(ret_V_9_reg_2227) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_fu_954_p2 = (($signed(ret_V_reg_2061) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign abscond_s_fu_1553_p2 = (($signed(ret_V_s_reg_2259) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign align_x = align_x_assign_cast_reg_1829;

assign align_x_assign_cast_fu_487_p1 = $signed(align_x_assign_fu_481_p2);

assign align_x_assign_fu_481_p2 = ($signed(i_reg_414) + $signed(4'd12));

assign align_y = $signed(align_y_assign_fu_833_p2);

assign align_y_assign_fu_833_p2 = ($signed(j_reg_425) + $signed(4'd12));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign exitcond1_fu_469_p2 = ((i_reg_414 == 4'd9) ? 1'b1 : 1'b0);

assign exitcond2_fu_495_p2 = ((j_reg_425 == 4'd9) ? 1'b1 : 1'b0);

assign exitcond3_fu_655_p2 = ((n_reg_449 == 5'd16) ? 1'b1 : 1'b0);

assign i_1_fu_475_p2 = (i_reg_414 + 4'd1);

assign i_cast_fu_465_p1 = i_reg_414;

assign j_1_fu_501_p2 = (j_reg_425 + 4'd1);

assign j_cast_fu_491_p1 = j_reg_425;

assign lhs_V_10_fu_1492_p1 = ref_imgs_V_q1;

assign lhs_V_11_fu_1590_p1 = ref_imgs_V_q0;

assign lhs_V_12_fu_1604_p1 = ref_imgs_V_q1;

assign lhs_V_13_fu_1679_p1 = ref_imgs_V_q0;

assign lhs_V_14_fu_1699_p1 = ref_imgs_V_q1;

assign lhs_V_1_fu_899_p1 = ref_imgs_V_q1;

assign lhs_V_2_fu_991_p1 = ref_imgs_V_q0;

assign lhs_V_3_fu_1005_p1 = ref_imgs_V_q1;

assign lhs_V_4_fu_1103_p1 = ref_imgs_V_q0;

assign lhs_V_5_fu_1117_p1 = ref_imgs_V_q1;

assign lhs_V_6_fu_1228_p1 = ref_imgs_V_q0;

assign lhs_V_7_fu_1248_p1 = ref_imgs_V_q1;

assign lhs_V_8_fu_1340_p1 = ref_imgs_V_q0;

assign lhs_V_9_fu_1354_p1 = ref_imgs_V_q1;

assign lhs_V_fu_885_p1 = ref_imgs_V_q0;

assign lhs_V_s_fu_1478_p1 = ref_imgs_V_q0;

assign n_1_fu_661_p2 = (n_reg_449 + 5'd1);

assign neg_10_fu_1569_p2 = (17'd0 - ret_V_10_reg_2266);

assign neg_11_fu_1637_p2 = (17'd0 - ret_V_11_reg_2298);

assign neg_12_fu_1658_p2 = (17'd0 - ret_V_12_reg_2305);

assign neg_13_fu_1725_p2 = (17'd0 - ret_V_13_reg_2317);

assign neg_14_fu_1740_p2 = (17'd0 - ret_V_14_reg_2328);

assign neg_1_fu_970_p2 = (17'd0 - ret_V_1_reg_2068);

assign neg_2_fu_1061_p2 = (17'd0 - ret_V_2_reg_2095);

assign neg_3_fu_1082_p2 = (17'd0 - ret_V_3_reg_2102);

assign neg_4_fu_1186_p2 = (17'd0 - ret_V_4_reg_2134);

assign neg_5_fu_1207_p2 = (17'd0 - ret_V_5_reg_2141);

assign neg_6_fu_1310_p2 = (17'd0 - ret_V_6_reg_2173);

assign neg_7_fu_1325_p2 = (17'd0 - ret_V_7_reg_2184);

assign neg_8_fu_1436_p2 = (17'd0 - ret_V_8_reg_2220);

assign neg_9_fu_1457_p2 = (17'd0 - ret_V_9_reg_2227);

assign neg_fu_949_p2 = (17'd0 - ret_V_reg_2061);

assign neg_s_fu_1548_p2 = (17'd0 - ret_V_s_reg_2259);

assign p_cast_fu_1799_p1 = $signed(tmp_s_fu_1793_p2);

assign p_shl1_cast_fu_720_p1 = tmp_37_fu_712_p3;

assign p_shl_cast_fu_708_p1 = tmp_36_fu_700_p3;

assign ret_V_10_fu_1500_p2 = (lhs_V_10_fu_1492_p1 - rhs_V_10_fu_1496_p1);

assign ret_V_11_fu_1598_p2 = (lhs_V_11_fu_1590_p1 - rhs_V_11_fu_1594_p1);

assign ret_V_12_fu_1612_p2 = (lhs_V_12_fu_1604_p1 - rhs_V_12_fu_1608_p1);

assign ret_V_13_fu_1687_p2 = (lhs_V_13_fu_1679_p1 - rhs_V_13_fu_1683_p1);

assign ret_V_14_fu_1707_p2 = (lhs_V_14_fu_1699_p1 - rhs_V_14_fu_1703_p1);

assign ret_V_1_fu_907_p2 = (lhs_V_1_fu_899_p1 - rhs_V_1_fu_903_p1);

assign ret_V_2_fu_999_p2 = (lhs_V_2_fu_991_p1 - rhs_V_2_fu_995_p1);

assign ret_V_3_fu_1013_p2 = (lhs_V_3_fu_1005_p1 - rhs_V_3_fu_1009_p1);

assign ret_V_4_fu_1111_p2 = (lhs_V_4_fu_1103_p1 - rhs_V_4_fu_1107_p1);

assign ret_V_5_fu_1125_p2 = (lhs_V_5_fu_1117_p1 - rhs_V_5_fu_1121_p1);

assign ret_V_6_fu_1236_p2 = (lhs_V_6_fu_1228_p1 - rhs_V_6_fu_1232_p1);

assign ret_V_7_fu_1256_p2 = (lhs_V_7_fu_1248_p1 - rhs_V_7_fu_1252_p1);

assign ret_V_8_fu_1348_p2 = (lhs_V_8_fu_1340_p1 - rhs_V_8_fu_1344_p1);

assign ret_V_9_fu_1362_p2 = (lhs_V_9_fu_1354_p1 - rhs_V_9_fu_1358_p1);

assign ret_V_fu_893_p2 = (lhs_V_fu_885_p1 - rhs_V_fu_889_p1);

assign ret_V_s_fu_1486_p2 = (lhs_V_s_fu_1478_p1 - rhs_V_s_fu_1482_p1);

assign rhs_V_10_fu_1496_p1 = alt_imgs_V_q1;

assign rhs_V_11_fu_1594_p1 = alt_imgs_V_q0;

assign rhs_V_12_fu_1608_p1 = alt_imgs_V_q1;

assign rhs_V_13_fu_1683_p1 = alt_imgs_V_q0;

assign rhs_V_14_fu_1703_p1 = alt_imgs_V_q1;

assign rhs_V_1_fu_903_p1 = alt_imgs_V_q1;

assign rhs_V_2_fu_995_p1 = alt_imgs_V_q0;

assign rhs_V_3_fu_1009_p1 = alt_imgs_V_q1;

assign rhs_V_4_fu_1107_p1 = alt_imgs_V_q0;

assign rhs_V_5_fu_1121_p1 = alt_imgs_V_q1;

assign rhs_V_6_fu_1232_p1 = alt_imgs_V_q0;

assign rhs_V_7_fu_1252_p1 = alt_imgs_V_q1;

assign rhs_V_8_fu_1344_p1 = alt_imgs_V_q0;

assign rhs_V_9_fu_1358_p1 = alt_imgs_V_q1;

assign rhs_V_fu_889_p1 = alt_imgs_V_q0;

assign rhs_V_s_fu_1482_p1 = alt_imgs_V_q0;

assign sum_3_cast_fu_823_p1 = sum_1_reg_437;

assign temp_sum_s_fu_1803_p2 = ($signed(sum_1_reg_437) + $signed(p_cast_fu_1799_p1));

assign tmp10_cast_fu_1618_p1 = $signed(tmp10_reg_2273);

assign tmp10_fu_1506_p2 = ($signed(abs_8_cast_fu_1453_p1) + $signed(abs_9_cast_fu_1474_p1));

assign tmp11_cast_fu_1627_p1 = $signed(tmp11_fu_1621_p2);

assign tmp11_fu_1621_p2 = ($signed(abs_cast_5_fu_1565_p1) + $signed(abs_10_cast_fu_1586_p1));

assign tmp12_cast_fu_1777_p1 = $signed(tmp12_fu_1771_p2);

assign tmp12_fu_1771_p2 = ($signed(tmp14_cast_fu_1767_p1) + $signed(tmp13_cast_fu_1758_p1));

assign tmp13_cast_fu_1758_p1 = $signed(tmp13_reg_2339);

assign tmp13_fu_1719_p2 = ($signed(abs_11_cast_fu_1654_p1) + $signed(abs_12_cast_fu_1675_p1));

assign tmp14_cast_fu_1767_p1 = $signed(tmp14_fu_1761_p2);

assign tmp14_fu_1761_p2 = ($signed(abs_13_cast_fu_1736_p1) + $signed(abs_14_cast_fu_1751_p1));

assign tmp1_cast_fu_1787_p1 = $signed(tmp1_reg_2234);

assign tmp1_fu_1394_p2 = ($signed(tmp5_cast_fu_1390_p1) + $signed(tmp2_cast_fu_1368_p1));

assign tmp2_cast_fu_1368_p1 = $signed(tmp2_reg_2148);

assign tmp2_fu_1144_p2 = ($signed(tmp4_cast_fu_1140_p1) + $signed(tmp3_cast_fu_1131_p1));

assign tmp3_cast_fu_1131_p1 = $signed(tmp3_reg_2109);

assign tmp3_fu_1019_p2 = ($signed(abs_cast_fu_966_p1) + $signed(abs_1_cast_fu_987_p1));

assign tmp4_cast_fu_1140_p1 = $signed(tmp4_fu_1134_p2);

assign tmp4_fu_1134_p2 = ($signed(abs_2_cast_fu_1078_p1) + $signed(abs_3_cast_fu_1099_p1));

assign tmp5_cast_fu_1390_p1 = $signed(tmp5_fu_1384_p2);

assign tmp5_fu_1384_p2 = ($signed(tmp7_cast_fu_1380_p1) + $signed(tmp6_cast_fu_1371_p1));

assign tmp6_cast_fu_1371_p1 = $signed(tmp6_reg_2195);

assign tmp6_fu_1268_p2 = ($signed(abs_4_cast_fu_1203_p1) + $signed(abs_5_cast_fu_1224_p1));

assign tmp7_cast_fu_1380_p1 = $signed(tmp7_fu_1374_p2);

assign tmp7_fu_1374_p2 = ($signed(abs_6_cast_fu_1321_p1) + $signed(abs_7_cast_fu_1336_p1));

assign tmp8_cast_fu_1790_p1 = $signed(tmp8_reg_2344);

assign tmp8_fu_1781_p2 = ($signed(tmp12_cast_fu_1777_p1) + $signed(tmp9_cast_fu_1755_p1));

assign tmp9_cast_fu_1755_p1 = $signed(tmp9_reg_2312);

assign tmp9_fu_1631_p2 = ($signed(tmp11_cast_fu_1627_p1) + $signed(tmp10_cast_fu_1618_p1));

assign tmp_10_fu_863_p2 = (tmp_3_reg_1930 | 9'd3);

assign tmp_11_fu_868_p3 = {{55'd0}, {tmp_10_fu_863_p2}};

assign tmp_12_fu_913_p2 = (tmp_3_reg_1930 | 9'd4);

assign tmp_13_fu_918_p3 = {{55'd0}, {tmp_12_fu_913_p2}};

assign tmp_14_fu_927_p2 = (tmp_3_reg_1930 | 9'd5);

assign tmp_15_fu_932_p3 = {{55'd0}, {tmp_14_fu_927_p2}};

assign tmp_16_fu_1025_p2 = (tmp_3_reg_1930 | 9'd6);

assign tmp_17_fu_1030_p3 = {{55'd0}, {tmp_16_fu_1025_p2}};

assign tmp_18_fu_1039_p2 = (tmp_3_reg_1930 | 9'd7);

assign tmp_19_fu_1044_p3 = {{55'd0}, {tmp_18_fu_1039_p2}};

assign tmp_20_fu_1150_p2 = (tmp_3_reg_1930 | 9'd8);

assign tmp_21_fu_1155_p3 = {{55'd0}, {tmp_20_fu_1150_p2}};

assign tmp_22_fu_1164_p2 = (tmp_3_reg_1930 | 9'd9);

assign tmp_23_fu_1169_p3 = {{55'd0}, {tmp_22_fu_1164_p2}};

assign tmp_24_fu_1274_p2 = (tmp_3_reg_1930 | 9'd10);

assign tmp_25_fu_1279_p3 = {{55'd0}, {tmp_24_fu_1274_p2}};

assign tmp_26_fu_1288_p2 = (tmp_3_reg_1930 | 9'd11);

assign tmp_27_fu_1293_p3 = {{55'd0}, {tmp_26_fu_1288_p2}};

assign tmp_28_fu_1400_p2 = (tmp_3_reg_1930 | 9'd12);

assign tmp_29_fu_1405_p3 = {{55'd0}, {tmp_28_fu_1400_p2}};

assign tmp_2_fu_827_p2 = (($signed(sum_3_cast_fu_823_p1) < $signed(sum_fu_122)) ? 1'b1 : 1'b0);

assign tmp_30_fu_1414_p2 = (tmp_3_reg_1930 | 9'd13);

assign tmp_31_fu_1419_p3 = {{55'd0}, {tmp_30_fu_1414_p2}};

assign tmp_32_fu_1512_p2 = (tmp_3_reg_1930 | 9'd14);

assign tmp_33_fu_1517_p3 = {{55'd0}, {tmp_32_fu_1512_p2}};

assign tmp_34_fu_1526_p2 = (tmp_3_reg_1930 | 9'd15);

assign tmp_35_fu_1531_p3 = {{55'd0}, {tmp_34_fu_1526_p2}};

assign tmp_36_fu_700_p3 = {{tmp_4_fu_695_p2}, {5'd0}};

assign tmp_37_fu_712_p3 = {{tmp_4_fu_695_p2}, {3'd0}};

assign tmp_38_fu_724_p2 = (p_shl_cast_fu_708_p1 - p_shl1_cast_fu_720_p1);

assign tmp_39_fu_730_p2 = (tmp_7_cast_reg_1842 + tmp_38_fu_724_p2);

assign tmp_3_fu_667_p3 = {{n_reg_449}, {4'd0}};

assign tmp_40_fu_740_p2 = (tmp_7_1_cast_reg_1847 + tmp_38_fu_724_p2);

assign tmp_41_cast_fu_735_p1 = $signed(tmp_39_fu_730_p2);

assign tmp_41_fu_750_p2 = (tmp_7_2_cast_reg_1852 + tmp_38_fu_724_p2);

assign tmp_42_cast_fu_745_p1 = $signed(tmp_40_fu_740_p2);

assign tmp_42_fu_755_p2 = (tmp_7_3_cast_reg_1857 + tmp_38_fu_724_p2);

assign tmp_43_cast_fu_877_p1 = $signed(tmp_41_reg_1968);

assign tmp_43_fu_760_p2 = (tmp_7_4_cast_reg_1862 + tmp_38_fu_724_p2);

assign tmp_44_cast_fu_881_p1 = $signed(tmp_42_reg_1973);

assign tmp_44_fu_765_p2 = (tmp_7_5_cast_reg_1867 + tmp_38_fu_724_p2);

assign tmp_45_cast_fu_941_p1 = $signed(tmp_43_reg_1978);

assign tmp_45_fu_770_p2 = (tmp_7_6_cast_reg_1872 + tmp_38_fu_724_p2);

assign tmp_46_cast_fu_945_p1 = $signed(tmp_44_reg_1983);

assign tmp_46_fu_775_p2 = (tmp_7_7_cast_reg_1877 + tmp_38_fu_724_p2);

assign tmp_47_cast_fu_1053_p1 = $signed(tmp_45_reg_1988);

assign tmp_47_fu_780_p2 = (tmp_7_8_cast_reg_1882 + tmp_38_fu_724_p2);

assign tmp_48_cast_fu_1057_p1 = $signed(tmp_46_reg_1993);

assign tmp_48_fu_785_p2 = (tmp_7_9_cast_reg_1887 + tmp_38_fu_724_p2);

assign tmp_49_cast_fu_1178_p1 = $signed(tmp_47_reg_1998);

assign tmp_49_fu_790_p2 = (tmp_7_cast_3_reg_1892 + tmp_38_fu_724_p2);

assign tmp_4_fu_695_p2 = (i_cast_reg_1816 + n_reg_449);

assign tmp_50_cast_fu_1182_p1 = $signed(tmp_48_reg_2003);

assign tmp_50_fu_795_p2 = (tmp_7_10_cast_reg_1897 + tmp_38_fu_724_p2);

assign tmp_51_cast_fu_1302_p1 = $signed(tmp_49_reg_2008);

assign tmp_51_fu_800_p2 = (tmp_7_11_cast_reg_1902 + tmp_38_fu_724_p2);

assign tmp_52_cast_fu_1306_p1 = $signed(tmp_50_reg_2013);

assign tmp_52_fu_805_p2 = (tmp_7_12_cast_reg_1907 + tmp_38_fu_724_p2);

assign tmp_53_cast_fu_1428_p1 = $signed(tmp_51_reg_2018);

assign tmp_53_fu_810_p2 = (tmp_7_13_cast_reg_1912 + tmp_38_fu_724_p2);

assign tmp_54_cast_fu_1432_p1 = $signed(tmp_52_reg_2023);

assign tmp_54_fu_815_p2 = (tmp_7_14_cast_reg_1917 + tmp_38_fu_724_p2);

assign tmp_55_cast_fu_1540_p1 = $signed(tmp_53_reg_2028);

assign tmp_56_cast_fu_1544_p1 = $signed(tmp_54_reg_2033);

assign tmp_5_fu_675_p1 = tmp_3_fu_667_p3;

assign tmp_6_10_fu_615_p2 = (j_cast_fu_491_p1 + 5'd12);

assign tmp_6_11_fu_625_p2 = (j_cast_fu_491_p1 + 5'd13);

assign tmp_6_12_fu_635_p2 = (j_cast_fu_491_p1 + 5'd14);

assign tmp_6_13_fu_645_p2 = (j_cast_fu_491_p1 + 5'd15);

assign tmp_6_1_fu_605_p2 = (j_cast_fu_491_p1 + 5'd11);

assign tmp_6_2_fu_515_p2 = (j_reg_425 + 4'd2);

assign tmp_6_3_fu_525_p2 = (j_reg_425 + 4'd3);

assign tmp_6_4_fu_535_p2 = (j_reg_425 + 4'd4);

assign tmp_6_5_fu_545_p2 = (j_reg_425 + 4'd5);

assign tmp_6_6_fu_555_p2 = (j_reg_425 + 4'd6);

assign tmp_6_7_fu_565_p2 = (j_reg_425 + 4'd7);

assign tmp_6_8_fu_575_p2 = (j_cast_fu_491_p1 + 5'd8);

assign tmp_6_9_fu_585_p2 = (j_cast_fu_491_p1 + 5'd9);

assign tmp_6_fu_680_p2 = (tmp_3_fu_667_p3 | 9'd1);

assign tmp_6_s_fu_595_p2 = (j_cast_fu_491_p1 + 5'd10);

assign tmp_7_10_cast_fu_611_p1 = tmp_6_1_fu_605_p2;

assign tmp_7_11_cast_fu_621_p1 = tmp_6_10_fu_615_p2;

assign tmp_7_12_cast_fu_631_p1 = tmp_6_11_fu_625_p2;

assign tmp_7_13_cast_fu_641_p1 = tmp_6_12_fu_635_p2;

assign tmp_7_14_cast_fu_651_p1 = tmp_6_13_fu_645_p2;

assign tmp_7_1_cast_fu_511_p1 = j_1_fu_501_p2;

assign tmp_7_2_cast_fu_521_p1 = tmp_6_2_fu_515_p2;

assign tmp_7_3_cast_fu_531_p1 = tmp_6_3_fu_525_p2;

assign tmp_7_4_cast_fu_541_p1 = tmp_6_4_fu_535_p2;

assign tmp_7_5_cast_fu_551_p1 = tmp_6_5_fu_545_p2;

assign tmp_7_6_cast_fu_561_p1 = tmp_6_6_fu_555_p2;

assign tmp_7_7_cast_fu_571_p1 = tmp_6_7_fu_565_p2;

assign tmp_7_8_cast_fu_581_p1 = tmp_6_8_fu_575_p2;

assign tmp_7_9_cast_fu_591_p1 = tmp_6_9_fu_585_p2;

assign tmp_7_cast_3_fu_601_p1 = tmp_6_s_fu_595_p2;

assign tmp_7_cast_fu_507_p1 = j_reg_425;

assign tmp_7_fu_854_p3 = {{55'd0}, {tmp_9_fu_849_p2}};

assign tmp_8_fu_686_p3 = {{55'd0}, {tmp_6_fu_680_p2}};

assign tmp_9_fu_849_p2 = (tmp_3_reg_1930 | 9'd2);

assign tmp_s_fu_1793_p2 = ($signed(tmp8_cast_fu_1790_p1) + $signed(tmp1_cast_fu_1787_p1));

always @ (posedge ap_clk) begin
    i_cast_reg_1816[4] <= 1'b0;
    tmp_7_cast_reg_1842[10:4] <= 7'b0000000;
    tmp_7_1_cast_reg_1847[10:4] <= 7'b0000000;
    tmp_7_2_cast_reg_1852[10:4] <= 7'b0000000;
    tmp_7_3_cast_reg_1857[10:4] <= 7'b0000000;
    tmp_7_4_cast_reg_1862[10:4] <= 7'b0000000;
    tmp_7_5_cast_reg_1867[10:4] <= 7'b0000000;
    tmp_7_6_cast_reg_1872[10:4] <= 7'b0000000;
    tmp_7_7_cast_reg_1877[10:4] <= 7'b0000000;
    tmp_7_8_cast_reg_1882[10:5] <= 6'b000000;
    tmp_7_9_cast_reg_1887[10:5] <= 6'b000000;
    tmp_7_cast_3_reg_1892[10:5] <= 6'b000000;
    tmp_7_10_cast_reg_1897[10:5] <= 6'b000000;
    tmp_7_11_cast_reg_1902[10:5] <= 6'b000000;
    tmp_7_12_cast_reg_1907[10:5] <= 6'b000000;
    tmp_7_13_cast_reg_1912[10:5] <= 6'b000000;
    tmp_7_14_cast_reg_1917[10:5] <= 6'b000000;
    tmp_3_reg_1930[3:0] <= 4'b0000;
end

endmodule //alignment_1
